"use client";

import { Activity, AlertTriangle, CheckCircle2, Clock3, RefreshCw, TrendingUp } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

import { consoleApi } from "./api";
import { EmptyState, PageHeader } from "./ConsoleShell";
import { useConsole } from "./ConsoleProvider";
import type { Analytics, SessionDetail, SessionPage, SystemStatus } from "./types";

export function SessionsPage() {
  const { sessions, refreshSessions } = useConsole();
  const [status, setStatus] = useState("");
  const filtered = status ? sessions.filter((item) => item.status === status) : sessions;
  return <><PageHeader eyebrow="Operations" title="Sessions" description="Tenant-scoped durable session records and confirmed outcomes." action={<button onClick={() => void refreshSessions()} className="inline-flex items-center gap-2 rounded-lg border border-ops-border bg-ops-raised px-3 py-2 text-xs"><RefreshCw className="h-3.5 w-3.5" />Refresh</button>} /><div className="p-5 lg:p-8"><label className="text-xs font-semibold">Status filter<select value={status} onChange={(event) => setStatus(event.target.value)} className="ml-3 rounded-lg border border-ops-border bg-ops-panel px-3 py-2"><option value="">All statuses</option><option>CREATED</option><option>ACTIVE</option><option>ENDING</option><option>ENDED</option><option>FAILED</option></select></label>{filtered.length ? <div className="mt-5 overflow-x-auto rounded-2xl border border-ops-border"><table className="w-full text-left text-sm"><thead className="bg-ops-panel text-[10px] tracking-wider text-ops-muted uppercase"><tr><th className="px-4 py-3">Prospect</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Qualification</th><th className="px-4 py-3">Updated</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.session_id} className="border-t border-ops-border hover:bg-ops-panel/70"><td className="px-4 py-4"><Link className="font-semibold text-ops-blue hover:underline" href={`/console/sessions/${item.session_id}`}>{item.customer.name}</Link><span className="block text-xs text-ops-muted">{item.customer.company ?? item.session_id.slice(0, 13)}</span></td><td className="px-4 py-4">{item.status}</td><td className="px-4 py-4">{item.buying_stage}</td><td className="px-4 py-4">{item.qualification_score}%</td><td className="px-4 py-4 text-ops-muted">{new Date(item.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="mt-5"><EmptyState title="No sessions found" detail="Change the filter or start an authenticated customer call." /></div>}</div></>;
}

export function SessionRecord({ sessionId }: { sessionId: string }) {
  const [record, setRecord] = useState<SessionDetail | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void consoleApi.sessionDetail(sessionId).then(setRecord).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Session could not be loaded.")); }, [sessionId]);
  return <><PageHeader eyebrow="Session record" title={record?.customer.name ?? "Loading session…"} description={record ? `${record.status} · ${record.buying_stage} · version ${record.version}` : "Loading the tenant-scoped durable projection."} action={<Link href="/console/sessions" className="rounded-lg border border-ops-border px-3 py-2 text-xs">Back to sessions</Link>} /><div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)] lg:p-8">{error ? <p role="alert" className="text-ops-red">{error}</p> : null}{record ? <><section className="rounded-2xl border border-ops-border bg-ops-panel p-5"><h2 className="text-sm font-bold">Transcript</h2>{record.transcript.length ? <ol className="mt-5 space-y-4">{record.transcript.map((message) => <li key={message.id} className="rounded-xl border border-ops-border bg-ops-base p-4"><p className="text-[10px] font-bold text-ops-muted">{message.speaker} · {new Date(message.created_at).toLocaleString()}</p><p className="mt-2 text-sm leading-6">{message.content}</p></li>)}</ol> : <div className="mt-5"><EmptyState title="No persisted turns" detail="Conversation turns will appear when processing begins." /></div>}</section><aside className="space-y-4"><Metric label="Qualification" value={`${record.qualification_score}%`} /><Metric label="Next best action" value={record.next_best_action?.replaceAll("_", " ") ?? "Awaiting discovery"} /><Metric label="Outcome" value={record.outcome?.replaceAll("_", " ") ?? "Unassigned"} /><section className="rounded-2xl border border-ops-border bg-ops-panel p-4"><h2 className="text-xs font-bold text-ops-muted uppercase">External actions</h2><p className="mt-3 text-sm">{record.operations.handoffs.length} handoff · {record.operations.meetings.length} meeting · {record.operations.followups.length} follow-up</p></section></aside></> : null}</div></>;
}

export function PerformancePage() {
  const [days, setDays] = useState(30);
  const [data, setData] = useState<Analytics | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { void consoleApi.analytics(days).then(setData).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Analytics are unavailable.")); }, [days]);
  return <><PageHeader eyebrow="Intelligence" title="Performance" description="Aggregated operational outcomes with no raw customer content." action={<select value={days} onChange={(event) => setDays(Number(event.target.value))} className="rounded-lg border border-ops-border bg-ops-panel px-3 py-2 text-xs"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select>} /><div className="p-5 lg:p-8">{error ? <p role="alert" className="text-ops-red">{error}</p> : null}{data ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Sessions" value={String(data.totals.sessions)} icon={Activity} /><Metric label="Conversion" value={`${data.conversion_rate}%`} icon={TrendingUp} /><Metric label="Avg qualification" value={`${data.totals.average_qualification}%`} icon={CheckCircle2} /><Metric label="Avg duration" value={`${Math.round(data.totals.average_duration_seconds / 60)} min`} icon={Clock3} /></div><section className="mt-6 rounded-2xl border border-ops-border bg-ops-panel p-5"><h2 className="text-sm font-bold">Outcome distribution</h2>{data.outcomes.length ? <div className="mt-5 space-y-3">{data.outcomes.map((item) => <div key={item.outcome} className="flex items-center gap-3"><span className="w-48 truncate text-xs text-ops-muted">{item.outcome.replaceAll("_", " ")}</span><div className="h-2 flex-1 rounded-full bg-ops-soft"><div className="h-full rounded-full bg-ops-blue" style={{ width: `${Math.max(3, item.count / data.totals.sessions * 100)}%` }} /></div><span className="w-8 text-right font-mono text-xs">{item.count}</span></div>)}</div> : <EmptyState title="No analytics yet" detail="Metrics appear after sessions are created." />}</section></> : <p role="status" className="text-sm text-ops-muted">Loading analytics…</p>}</div></>;
}

export function SystemPage() {
  const [data, setData] = useState<SystemStatus | null>(null);
  useEffect(() => { void consoleApi.system().then(setData); }, []);
  return <><PageHeader eyebrow="Administration" title="System" description="Safe runtime readiness; secrets and mutable deployment configuration are intentionally excluded." /><div className="p-5 lg:p-8">{data ? <><div className={`rounded-2xl border p-5 ${data.status === "ok" ? "border-ops-green/30 bg-ops-green/5" : "border-ops-amber/30 bg-ops-amber/5"}`}><p className="text-xs text-ops-muted">Overall readiness</p><p className="mt-2 text-2xl font-bold capitalize">{data.status}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(data.checks).map(([name, value]) => <Metric key={name} label={name} value={value} icon={value === "ok" || value === "available" ? CheckCircle2 : AlertTriangle} />)}<Metric label="Schema" value={data.schema_revision} /></div></> : <p role="status" className="text-sm text-ops-muted">Loading system readiness…</p>}</div></>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon?: typeof Activity }) {
  return <div className="rounded-2xl border border-ops-border bg-ops-panel p-5">{Icon ? <Icon className="h-5 w-5 text-ops-blue" /> : null}<p className="mt-3 text-[10px] font-bold tracking-wider text-ops-muted uppercase">{label}</p><p className="mt-2 text-xl font-bold capitalize">{value.toLowerCase()}</p></div>;
}
