"""Versioned domain models for sales-session state and durable records."""

from .identifiers import UUID7, new_uuid7
from .models import (
    Customer,
    DomainEvent,
    MemoryFact,
    Message,
    Objection,
    Outcome,
    Qualification,
    Requirement,
    SalesState,
    ToolCall,
)
from .types import (
    BuyingStage,
    EventType,
    MemoryField,
    MessageSource,
    NextBestAction,
    ObjectionCategory,
    ObjectionStatus,
    OutcomeType,
    RequirementField,
    RequirementUpdateSource,
    SessionStatus,
    Speaker,
    ToolCallStatus,
)

__all__ = [
    "UUID7",
    "BuyingStage",
    "Customer",
    "DomainEvent",
    "EventType",
    "MemoryFact",
    "MemoryField",
    "Message",
    "MessageSource",
    "NextBestAction",
    "Objection",
    "ObjectionCategory",
    "ObjectionStatus",
    "Outcome",
    "OutcomeType",
    "Qualification",
    "Requirement",
    "RequirementField",
    "RequirementUpdateSource",
    "SalesState",
    "SessionStatus",
    "Speaker",
    "ToolCall",
    "ToolCallStatus",
    "new_uuid7",
]
